server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: 'User_web_Access'
  datasource:
    driver-class-name: org.h2.Driver
    password: kajol@123
    url: jdbc:h2:mem:testdb
    username: kajol
  h2:
    console:
      enabled: true  
      path: /h2-console  
  boot:
    admin:
      client:
        url: http://localhost:1111/    
  redis:
    host: 127.0.0.1     # Replace with your Redis server host or IP address
    port: 6379         # Replace with the Redis server por        # (Optional) Replace with the Redis server password, if required
    database: 0         
